# Generated by Django 5.0.6 on 2024-05-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_content_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='content',
            new_name='contents',
        ),
    ]
